### PR TITLE
Consider case when both Optional & apiReturnType is used #410

### LINKED ISSUE #410: useOptionalForNullableReturnTypes conflicts with apiReturnType (Version: 4.0.0)
## Issue Description

If you set both useOptionalForNullableReturnTypes and apiReturnType to true, the generator ignores apiReturnType.

## Steps to Reproduce

```kotlin
tasks.named<io.github.kobylynskyi.graphql.codegen.gradle.GraphQLCodegenGradleTask>("graphqlCodegen") {
  ...
  apiReturnType = "java.util.concurrent.CompletionStage"
  useOptionalForNullableReturnTypes = true
}
```

## Expected Result

```java
@javax.annotation.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2020-11-30T13:39:15+0000"
)
public interface QueryResolver {

    java.util.concurrent.CompletionStage<java.util.Optional<Publisher>> example(String id, graphql.schema.DataFetchingEnvironment env) throws Exception;

}
```

## Actual Result
```java
@javax.annotation.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2020-11-30T13:39:15+0000"
)
public interface QueryResolver {

    java.util.Optional<Publisher> example(String id, graphql.schema.DataFetchingEnvironment env) throws Exception;

}
```

## Your Environment and Setup

* **graphql-java-codegen**: 4.0.0
* **Build tool**:  Gradle
* **Java tool**: 1.8.0_242
* **Mapping Config**: see above

### PR DESCRIPTION
**Pull request by kobylynskyi**
Fixes #410

### CODE REVIEW

File: src/test/resources/expected-classes/optional/NodeQueryResolver_mono.java.txt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+
+@javax.annotation.Generated(
+    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
+    date = "2020-12-31T23:59:59-0500"
+)
+public interface NodeQueryResolver {
+
+    reactor.core.publisher.Mono<java.util.Optional<Node>> node(String id) throws Exception;
```
Comment (jxnu-liguobin) [inline src/test/resources/expected-classes/optional/NodeQueryResolver_mono.java.txt:8]: Mono itself can describe 0 or 1 in reactor.Users of the stream should be aware of this.

File: src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphqlTypeToJavaTypeMapper.java [hunk 2]
```diff
@@ -296,67 +295,68 @@ private static String wrapSuperTypeIntoList(MappingContext mappingContext, Strin
...
-                    // in case it is query/mutation, return type is list and apiReturnListType is set
-                    return javaTypeName.replace(SCALA_UTIL_LIST, mappingContext.getApiReturnListType());
-                }
-                if (Utils.isNotBlank(mappingContext.getApiReturnType())) {
-                    // in case it is query/mutation and apiReturnType is set
-                    return getGenericsString(mappingContext, mappingContext.getApiReturnType(), javaTypeName);
-                }
-            }
-            if (javaTypeName.startsWith(JAVA_UTIL_LIST) &&
+            if (computedTypeName.startsWith(JAVA_UTIL_LIST) &&
```
Comment (jxnu-liguobin) [inline src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphqlTypeToJavaTypeMapper.java:329]: Can  use `switch` ? I'm implementing kotlin, and there's going to be a lot of conflict.

Comment (kobylynskyi) [reply src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphqlTypeToJavaTypeMapper.java:329]: @jxnu-liguobin before implementing kotlin we need to refactor the code to make it simple for further extensions. I was thinking to do it later next week. So please don't do kotlin yet :)

File: src/test/resources/expected-classes/optional/NodeQueryResolver_mono.java.txt (hunk 1 above)
Comment (kobylynskyi) [reply src/test/resources/expected-classes/optional/NodeQueryResolver_mono.java.txt:8]: Yes, you are right. But have you seen the bug description? There could be some types that can expect Optional as a sub-type. Anyway, this Optional thing can be disabled. That's up to the client to decide.

File: src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphqlTypeToJavaTypeMapper.java (hunk 2 above)
Comment (jxnu-liguobin) [reply src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphqlTypeToJavaTypeMapper.java:329]: In fact, the templates and code have been written https://github.com/jxnu-liguobin/graphql-java-codegen/tree/kotlin/src/main/resources/templates/kotlin-lang (In addition to the unit test, the rest are basically ready
), but there is still one problem that has not been solved. I am ready to wait until you refactor.

one problem is due to the strict restrictions of kotlin, overriding the parent class must show adding `override`, which is different from the Scala and Java, which makes it may need record all abstract methods of the parent class.

```kotlin
package com.github.graphql

import kotlin.properties.Delegates
import com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer
import java.util.StringJoiner

@javax.annotation.Generated(
    value = ["com.kobylynskyi.graphql.codegen.GraphQLCodegen"],
    date = "2020-12-31T23:59:59-0500"
)
open class GithubReopenedEventTO(
    @JvmField private var actor: GithubActorTO,
    @javax.validation.constraints.NotNull
    @JvmField private var closable: GithubClosableTO,
    @javax.validation.constraints.NotNull
    @JvmField private var createdAt: String,
    @javax.validation.constraints.NotNull
    @JvmField private var id: String
) : GithubIssueTimelineItemsTO, GithubPullRequestTimelineItemsTO, GithubIssueTimelineItemTO, GithubPullRequestTimelineItemTO, GithubNodeTO {

    fun getActor(): GithubActorTO {
        return actor
    }
    fun setActor(actor: GithubActorTO) {
        this.actor = actor
    }
    fun getClosable(): GithubClosableTO {
        return closable
    }
    fun setClosable(closable: GithubClosableTO) {
        this.closable = closable
    }
    fun getCreatedAt(): String {
        return createdAt
    }
    fun setCreatedAt(createdAt: String) {
        this.createdAt = createdAt
    }
    fun getId(): String { // if super has it, must add `override`,like : override fun getId()
        return id
    }
    fun setId(id: String) {
        this.id = id
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null || javaClass != other.javaClass) {
            return false
        }
        val that = other as GithubReopenedEventTO
        return Objects.equals(actor, that.actor)
            && Objects.equals(closable, that.closable)
            && Objects.equals(createdAt, that.createdAt)
            && Objects.equals(id, that.id);
    }

    override fun hashCode(): Int {
        return Objects.hash(actor, closable, createdAt, id);
    }

    // In the future, it will change.
    override fun toString(): String {
        val joiner = StringJoiner(", ", "{ ", " }")
        joiner.add("actor: " + GraphQLRequestSerializer.getEntry(actor))
        joiner.add("closable: " + GraphQLRequestSerializer.getEntry(closable))
        joiner.add("createdAt: " + GraphQLRequestSerializer.getEntry(createdAt))
        joiner.add("id: " + GraphQLRequestSerializer.getEntry(id))
        return joiner.toString()
    }

    class Builder {

        private lateinit var actor: GithubActorTO
        private lateinit var closable: GithubClosableTO
        private lateinit var createdAt: String
        private lateinit var id: String

        fun setActor(actor: GithubActorTO): Builder {
            this.actor = actor
            return this
        }

        fun setClosable(closable: GithubClosableTO): Builder {
            this.closable = closable
            return this
        }

        fun setCreatedAt(createdAt: String): Builder {
            this.createdAt = createdAt
            return this
        }

        fun setId(id: String): Builder {
            this.id = id
            return this
        }

        fun build(): GithubReopenedEventTO {
            return GithubReopenedEventTO(actor, closable, createdAt, id)
        }
    }
}
```
